### ISSUE TITLE
Add links to server-config-checklist.md

### ISSUE THREAD

**Issue by icevans** [icevans/linux-study-group#1]
We need to add links to good resources with detailed explanations of how to carry out the steps on the server-config-checklist

**Comment by jkurthoconnor** [comment]
Is this still an open issue Ian? It seems some links have been added already.

**Comment by icevans** [comment]
Yes, I think I should close this issue, although if you think there are places where we could add additional/alternative links feel free to add them and submit a PR!

**Comment by jkurthoconnor** [comment]
I think I could find one or two more to add, and I'll be happy to do so. If nothing else, the 'Servers for Hackers' series you posted in the forum could be pulled in to the checklist. But as it stands, the written explanations are pretty complete.

**Comment by jkurthoconnor** [comment]
Ok. PR #10 is my shot at capturing the supplemental links before they disappear.
